### ISSUE TITLE
ide-haskell / atom-haskell org

### ISSUE THREAD

**Issue by lierdakil** [ranjitjhala/hover-tooltips-hdevtools#1]
Hi. I wondered if you'd be interested in incorporating hdevtools support into ide-haskell stack.

Thanks for your time.

**Comment by ranjitjhala** [comment]
Hi,

yes! that was my plan -- to ultimately write an hdevtools
backend for ide-haskell. I wrote these two plugins as smaller
pieces just to get a feel for how to write atom packages etc.,
and refactor further into smaller pieces. (I think ghc-mod does
various things that hdevtools does not, so will have to figure
out how to suitably structure the 'ide-backend'.)

But at any rate, yes -- I'd like very much to have an hdevtools
backend (and will probably get to it in a few weeks when I have
some cycles.)

Thanks!

On Sat, Jul 4, 2015 at 7:06 AM, Nikolay Yakimov notifications@github.com
wrote:

> Hi. I wondered if you'd be interested in incorporating hdevtools support
> into ide-haskell stack.
> 
> Thanks for your time.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ranjitjhala/hover-tooltips-hdevtools/issues/1.

## 

Ranjit.

**Comment by lierdakil** [comment]
I've sent you an invitation to atom-haskell org. Don't hesitate to contact me if you have any questions (preferably by e-mail, see github profile)
